spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal-app/data/database/config'
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "internal-app/data/database/config" -}}
              {{ range $k, $v := .Data.data }}
                  export {{ $k }}={{ $v }}
              {{ end }}
          {{- end }}